apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: aws-secret
  namespace: '{{ .Values.repo }}-development'
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCVbgsQgvIxzOWI43ydmWN+M9ySfGjB82AnEtBtvXNDPs8aguwHai5lVZ973A6FbXbY/3l65hPn4mL11J60fzZErpsfHMcyCaezEg6tBcQ9ww/TvtD+yOl3Px0+TLSocSy4I1yKKcTHCEJoHr8lQ9E9rU4BY2TEJBtQOThqSEeFckibeOJA92WFGl0qvU28UI3fx6z7t+Wv9l4CJmEOxniBgCD6nYg7RCX2aYHjQeKeWebUjJ4rJEq4K6/mLQxB75bZp/hwcXr56cSAqV43jb7HIHotd1mkJkm7OSJosp5g6I7375vnrwX9NTg4PUFXFZuh6B+9YCuJQytY0TB/X+4VPfRZVEICDUDwhypM2SnOjRnKVHfmcfcCMNI5n+r/h6eh2ToR3yuDpk7YmCgGnx1N8zUGsxRUREo/CdmkJdiHVUEWuSNgzF39MprtiTS8j7l3lbbiHlLyynnza2jxfaVTYDs+37++QfrK3BNsQSYh8ZFpDFRCXFxCtLeMUbyBj5b1mKgT1bxKDYZzd+yoWICzzZHGyZWQ2ReKSnSZJKO2rXMWkmVE70vH1Jz793XGRx/upq6dfvJ94HxA/w0U3nagJ9SGHqypwn1pYKs2EBAEOJz/pSGoFjXXpS4/ZovjJAeTWGz2yHWpIUDqWi/FG8DPY3lLp6rETL+5RNzccdCVO8AREjGOkOg8tsK4kdRd553iFAJCdnZynukdw5yAEPfZIVjycw==
    AWS_SECRET_ACCESS_KEY: AgAbjuT/CmTLOWzPpurZGXe4nlEg/S2pMVcLA3VIo/qqA6uBfFDcoJStvNsgJyM0sw9j0ZS4qH4Yic26lfN6o04SpJ7uNsa7s2pYBqA+gS7kxTgz2qJf2AJ0q/4gfL98H0MEi4+ZUcwWsGXPLcNooaTs5aSM76Cidtn2NzeQqQPIm8s6uHwJNFYljfJJdlyHJrov+mRQoWwaZ+Xrm/ji8PTiX1HC36xFXgz6YfXH+FwgAHhFwY+QYbDAsMuLFW5O0sSEuqNGMbcEswrbgA+TrInO7vWSmUFXlI8AS+Wmf/9ZaNrGflr+ocgQtD1r/2tlj4lFAdXCFtXJ/Fuuu+GrT3mebRXlsEelOkbweBuhvaHFJWrV5jLc4BWqpT+xyGfj6i40zGY2/l3iuAuRpgZx+irJzc268CUH9HxMO1g4/Vu2x2lXgvKKhid8RcO3COkIVaFWoWMqPSez+H3zKbHi4SvFRJpFvuuRoX87/wwOpzy6BPKRhdK27TQuKmaGzhO9mdBTVmyyXzNSPLXN4D2cwZlzoFEIFftetKIu3wSWgZcOH+OOW2++BcY+8/kPAZfYWdsYGfi3LNv848C5VcQT0JAYcvhLbdbPN0xBaeFY2iJHcJz/HHorsn6znI0OEEQfB1YXElApW43a7xgWBKmadTEVwCED74rEb/cnuznHbnv+CLkPA5ObC9RmiAtJJjEXD4C+n+qrJ++828tfEQ4dE0/wWFu+RaDoXnrylsyjR3QAM6wtb6NdDd+T
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: aws-secret
      namespace: '{{ .Values.repo }}-development'
    type: Opaque
