# Secret to manage AWS ECR
# This is a secret with minimal permissions, only needed to interact with AWS ECR
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: {{ .Values.repo }}-development
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.secret.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret.AWS_SECRET_ACCESS_KEY }}