# This secret is used by the pipeline service account to clone the repository and run the piipeline
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-github
  namespace: {{ .Values.repo }}-ci-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/{{ .Values.org }}/{{ .Values.repo }}
  password: {{ .Values.github.secrets.repositories }}
  username: not-used
