#FROM registry.access.redhat.com/ubi8/ubi:8.5
FROM registry.access.redhat.com/ubi8/nodejs-16
USER root

ADD ZscalerRootCA.crt /etc/pki/ca-trust/source/anchors/ZscalerRootCA.crt
RUN chmod 644 /etc/pki/ca-trust/source/anchors/ZscalerRootCA.crt && update-ca-trust

ENV AWSCLI_VERSION=1.24.10 \
    AWSCLI_USER=nonroot \
    AWSCLI_WORKDIR=/home/nonroot \
    YUM_OPTS="--setopt=install_weak_deps=False --setopt=tsflags=nodocs" \
    PIP_OPTS="--force-reinstall --no-cache-dir"

COPY helpers/* /usr/bin/

RUN dnf install ${YUM_OPTS} -y python3-pip nss_wrapper wget openssh-clients openssl tar unzip git findutils gzip && \
    dnf -y clean all && \
    pip3 install ${PIP_OPTS} awscli==${AWSCLI_VERSION} 
    
RUN wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
RUN unzip terraform_0.11.11_linux_amd64.zip
RUN mv terraform /usr/local/bin/

RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm && chmod +x /usr/local/bin/helm

RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq

RUN useradd -m -g 0 ${AWSCLI_USER} && \
    chgrp -R 0 ${AWSCLI_WORKDIR} && \
    chmod -R g+rwX ${AWSCLI_WORKDIR}

USER ${AWSCLI_USER}

WORKDIR ${AWSCLI_WORKDIR}

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD [ "/bin/bash" ]