apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-admin-auth
  namespace: argocd
spec:
  encryptedData:
    GITHUB_CREDENTIALS: AgBv9wIVVuXnnOfrd6z8DIeOgr6aQ6U++7Kq/KnKViafdsHwWmM33BkMCGKcUEdYxd54yJUFRmUJygIXZfzMg+BFMWLGNJlH/OPTicMguUz2Cw9EUUktWmolILEFKmE82+hFXJAwyC/80m2zNwlRQHsnLoCNWJwK/jV080Gk3klr2z8OuejvGN9HTgKa6Pnqb1+2r6+rHntRU/gJvywmanStd7jZCFkiXICTWwCHNJFGt7tPNFA4Sgd1ScJLLoCBfnyZqrb5DVVoqxEJuMpwOb823SZELEAgSgPJND01eAb5xKDPOLKgjlKcDDx9KLg+EByIircbYpy/Ll4c61jeM01+dmaATLcVyCsDVSJ3tyRMLRBp11Xi+25XnuoeXoETdx9QFrdATCQiG4F+qErzVH6Pb3EBrop3f8qVWk204l+GK4hNG0tNnZm8HItqrsPcLHRnG7vyw77xPJTN5khkMALDj8NEHxXOQTBqwB/hKvr5IL5idBVIOdWbIzK6v4JgFhn0Sh1ua8S3wKltWMGITxhPFgklqGE6Mk9+Oc6kp73sDEzFM9XexQEknZeWk9sTFT9AGyDm/fonFTGnkzIMOI6LzX/bMM+OoRlKNwPn1t+6aef9ek7nCFZUsIryqlrltJDFdoUWZRAm8zN+nkJzMvCuT3lkIR5HWBB5MiZETjRX0GA/qRBZNnQ0jiq+FKrbCp2bPh3+q/vbN2RSDGSn+ppM9jA6EpKtk0ozpMByfPyKxzfckB7cd2te
  template:
    metadata:
      creationTimestamp: null
      name: github-admin-auth
      namespace: argocd
    type: Opaque
---
